### ISSUE TITLE
Improve title matching

### ISSUE THREAD

**Issue by ciwy85** [sleeyax/stremio-easynews-addon#30]
I know it's an ongoing battle but here are couple of examples that I have found:
Despicable me 4 shows resoults for other parts eg. Part 2 and 3 first.
Polish tv series Janosik doesn't match episodes numbers correctly as well as showing more episode resoults when searching for movie with the same title (its a tv series made of a movie).

**Comment by sleeyax** [comment]
Duplicate of: #25.
