### ISSUE TITLE
Improve search for series with only one season

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-easynews-addon#31]
For example: polish tv series `Janosik` only has one season. If you search for `Janosik E13` you can find results on EN web. The addon only searches for `S01E13`, which yields no results.

**Comment by mikmc55** [comment]
polish, single series from 1974.. that is why the search catalog is included and it does catch these episodes

**Comment by mikmc25** [comment]
polish, single series from 1974.. that is why the search catalog is included and it does catch these episodes
solution is use the search catalog in the addon
