### ISSUE TITLE
Video playback issues since 1.3.0

### ISSUE THREAD

**Issue by Screamio** [sleeyax/stremio-easynews-addon#33]
I'm using a nVidia Shield together with Stremio and Easynews Plus.
It worked fine with version 1.2.0, but since upgrading to 1.3.0 only specific files are playing.
Most files I select load without ever getting started, no matter how long I wait.

It looks like only popular and media currently being watched by many people is working with v1.3.0 on Android TV.

No VPN was used when testing and I have no issues with RD services.
Contact me if more information is needed.

**Comment by sleeyax** [comment]
That's impossible, nothing particular changed in v1.3.0 that could cause this issue. Try reinstalling.

**Comment by Screamio** [comment]
Troubleshooted the behavior.
It works much better when the addon is selfhosted, everything seems better now.
