### ISSUE TITLE
Improve results for foreign shows

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-easynews-addon#35]
From [reddit](https://www.reddit.com/r/StremioAddons/comments/1ehrrdg/comment/lhlpiw3/):

> The update to 1.3.0 removed foreign language content. I tried multiple German ,tv shows and movies, zero results. Even for episode i watched the other day. When I do the same search for US shows everything is working as should.

> It's Asphalt-cowboys , Benjamin Blumchen, Switch Reloaded so far.

**Comment by mikmc55** [comment]
these shows are not sourced by any addon, i have multiple installed atm and there are 0 sources bar the odd episode on the cf version

**Comment by sleeyax** [comment]
Thanks for verifying. The issue can be closed then.
