### ISSUE TITLE
Seeing different results depending on client

### ISSUE THREAD

**Issue by Raislog** [sleeyax/stremio-easynews-addon#40]
Not sure how often this happens, I don't usually compare against different devices/clients but I noticed this today:

Self hosted addon

Searching for Slow Horses S04E01

On desktop stremio, addon returns maybe 5 total results.
On two separate android TV setups (Firestick / Nvidia Shield) addon returns many more results (20+) 
Still not showing all results available on easynews search. These episodes get 'cleaned/taken down' fast so i'm not sure you'll be able to test behavior if too much time passes.

I checked the self host docker logs and it doesn't seem to provide anything useful. I wanted to compare hit counts between the devices as reported to console log, but couldn't find that. Let me know if there's a different place to look.

**Comment by sleeyax** [comment]
Hmm that shouldn't even be possible. Stremio calls the addon the same way. Maybe there used to be 5 results in fact, then it got cached on desktop, and then it got more results, which only show up on other devices with different caches.

**Comment by Raislog** [comment]
I tried completely closing stremio and re-opening to rule out a cache issue, but that may be culprit? i'm not sure how to ensure it is clear. For Example its been 3 hours and I just went back to the desktop, started stremio client and its still showing 5 results.

**Comment by mikmc55** [comment]
find the location you have set your cache folder in stremio settings then just clear or delete it

**Comment by Raislog** [comment]
Doesn't change anything. This is the only addon that behaves like this. The other easynews addone correctly updates.

I'm going to fully remove the self hosted container to see if that resets it.
