### ISSUE TITLE
Strange Outgoing Data

### ISSUE THREAD

**Issue by JellyEyedJim** [sleeyax/stremio-easynews-addon#42]
system: macOS Sonoma, stremio desktop client, macOS activity monitor network section

When opening an Easynews stream, a large amount of outgoing data is output. It almost uses as much upload to access Easynews content as it does download.

This is measured with activity monitor on macOS. The addon has been installed through the publicly hosted instance.

This behavior does not occur when using other stremio addons such as torrentio.

**Comment by sleeyax** [comment]
I don't think this is an issue with the addon. More like the way Easynews works. 

I don't have a mac so I can't see what you mean without seeing a screenshot.

**Comment by JellyEyedJim** [comment]
Figured it out.

Easynews+ seems to work by accessing their servers via https, before a loopback proxy into http for the stremio player. I was simply measuring the loopback traffic.

Why is this loopback necessary at all? Torrentio provides stremio with https links directly.

**Comment by sleeyax** [comment]
I don't know what you mean by loopback proxy. The addon returns https links directly from Easynews, similar to Torrentio + RD.

**Comment by JellyEyedJim** [comment]
Your plugin reroutes through 127.0.0.1

**Comment by sleeyax** [comment]
> Your plugin reroutes through 127.0.0.1

Prove it because it literally doesn't... You can check the code

**Comment by sleeyax** [comment]
Maybe you're talking about Stremio streaming server (on port 11470 IIRC)? That's a part of Stremio and unrelated to this addon.

**Comment by JellyEyedJim** [comment]
I’ve tested the above and Torrentio does not use 127.0.0.1

Try this:

1. Open an Easystream+ stream in stremio
2. Right click on the playing video and copy the stream link

Your link will resemble http://127.0.0.1:11480/proxy/d=https######members.easynews.com&

Then using Torrentio

1. Open Torrentio stream in stremio
2. Right click on the playing video and copy streaming link

Your link will resemble https://torrentio.strem.fun/yadayada

**Comment by sleeyax** [comment]
I see. Well in any case it's not something the addon can control. Maybe Stremio decides to proxy it through the streaming server because it requires http headers to be set, or it could be some other reason I don't know without checking the Stremio source code. Don't worry about it.
