### ISSUE TITLE
Not returning any rersults

### ISSUE THREAD

**Issue by MrKaon** [sleeyax/stremio-easynews-addon#43]
It happened recently, not long ago; I am not sure why it doesn't return search results any more. I have an active account with unlimited bandwidth, and it works fine with Kodi (Fen light add-on) but not on Stremio; I tried it on PC, Android TV and phone. 

I don't know how can I get a log for it but I am happy to help anyway to fix this bug.

PS.
No result with other EasyNews add-on as well.

**Comment by sleeyax** [comment]
Easynews changed something that breaks both addons. I'll look into it later today.
