### ISSUE TITLE
Suddenly receiving 401 unauthorized message

### ISSUE THREAD

**Issue by Raislog** [sleeyax/stremio-easynews-addon#45]
Just noticed today that I wasn't getting any results from the addon (i've been selfhosting it and its been running fine for a long time). I updated to 1.3.1 a couple weeks ago and have had no issues. I thought I would restart the addon, when that didn't look i checked the container logs:

Same error received for every 'search'
{
  message: 'failed to handle stream',
  error: Error: Failed to fetch search results of query 'TITLE_OF_SHOW_HERE': 401 Unauthorized
      at EasynewsAPI.search (/app/packages/api/dist/api.js:43:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async /app/packages/addon/dist/addon.js:111:19,
  context: { resource: 'stream', id: 'tt1684562', type: 'movie' }
}

I removed / readded the addon, checked credentials, etc. Then i even used the public instance and its still returning no results. I thought something changed on the easynews side, but the other easynews addon is still working.
Not sure what is going on.

**Comment by sleeyax** [comment]
It's because they patched this  https://github.com/sleeyax/stremio-easynews-addon/pull/44

**Comment by sleeyax** [comment]
Can't reproduce this anymore. Can you? Maybe it was a temporary auth issue on their end.

**Comment by Raislog** [comment]
I saw your comment and checked my setup again. It was still having the unauthorized issue on 1.3.1 

I pulled 1.3.2 and everything is working again. So all good with latest update.
