### ISSUE TITLE
easynews+ 1.3.2 won't work and find sources simultaneously on 2 stremio users also working profile lag and freeze every second its unbearable

### ISSUE THREAD

**Issue by itzikvil** [sleeyax/stremio-easynews-addon#48]
Hi,

I used to have (about 3-4 monts ago) multiple stremio accounts in the past (with paid easynews account) to which i installed easynews+1.3.2 addon and everything worked great. i got sources from both stremio accounts and streaming was smooth from easynews (i am a paid customer).
I renewed my easynews paid account and installed addon on 2 stremio accounts and the following happen which i don't know how to handle:
- while searching a movie (wild robot for instance) with first stremio account i get many sources as it should though while pressing the sources it takes long time for movie to begin (as opposed to the past) and when movie start playing its just stuck every 1 second which make it unbearable and unusable to work with.
- my other account have the same configuration that is what baffle me and when i search same movie (wild robot) i dont get any sources at all.
i realy tried everything i could have think off:
- removing all addons and reinstalling all.
- resetting addons to default and install ONLY easynews+ v1.3.2 and search > no go same results.
- removing all together stremio and reinstalling.
- also tried working from my cell phone with stremio checked both profiles same results.
i would like to add that i have no connection issues what so ever not on my cellular and not of my computer as torrentio streams work great even on 4K.
none of this helped and i beginning to think something is fishy here hence i turn to you guys as you are the experts.

thanks,

looking forward to your reply,
p.s: let me know in case any info needed.
itzikv

short update:
while removing my easynews v1.3.2 from stremio today and then installing again my account cant find any sources anymore so i guess something changed in the add-on or the stremio application hence things aren`t working. hope i am the only one with this problem. looking forward to your assistance with regard.

**Comment by itzikvil** [comment]
https://www.reddit.com/r/StremioAddons/comments/1g3wb1k/easynews/ another one with same error i get. please help us we paid 1.5 to easynews only to work with your addon :/ now we cant.

i am sure you can solve it. we are counting on you guys 👍

**Comment by sleeyax** [comment]
Seems to be working on my end. What instance are you using (public, self-hosted, other)? 

![image](https://github.com/user-attachments/assets/edc59d8b-b437-4f97-8d76-514e2f509b39)

FYI I'm not affiliated with EasyNews. 

PS your issue is super long to read, easily could've been a couple sentences instead :sweat_smile:

**Comment by itzikvil** [comment]
Lol i had to describe all background.

Anyhow thanks for getting back to me.

Problem was solved i found what was causing search to fail. It was apparently my password which was not accepted on easynews although it was working on the web page/easynews site. I press change the passwird got it to my mail and now the search is working great. Thanks again for replying back in a fashinable way.
